### ISSUE TITLE
pg_dump doesnt work

### ISSUE THREAD

**Issue by nshmn** [postgrespro/zson#15] opened 2019-01-08 12:00 UTC
> pg_dump -Fc -v bittrex > newtry3
pg_dump: last built-in OID is 16383
pg_dump: reading extensions
pg_dump: identifying extension members
pg_dump: reading schemas
pg_dump: reading user-defined tables
pg_dump: reading user-defined functions
pg_dump: reading user-defined types
pg_dump: reading procedural languages
pg_dump: reading user-defined aggregate functions
pg_dump: reading user-defined operators
pg_dump: reading user-defined access methods
pg_dump: reading user-defined operator classes
pg_dump: reading user-defined operator families
pg_dump: reading user-defined text search parsers
pg_dump: reading user-defined text search templates
pg_dump: reading user-defined text search dictionaries
pg_dump: reading user-defined text search configurations
pg_dump: reading user-defined foreign-data wrappers
pg_dump: reading user-defined foreign servers
pg_dump: reading default privileges
pg_dump: reading user-defined collations
pg_dump: reading user-defined conversions
pg_dump: reading type casts
pg_dump: reading transforms
pg_dump: reading table inheritance information
pg_dump: reading event triggers
pg_dump: finding extension tables
pg_dump: finding inheritance relationships
pg_dump: reading column info for interesting tables
pg_dump: finding the columns and types of table "public.test"
pg_dump: finding the columns and types of table "public.zson_dict"
pg_dump: finding default expressions of table "public.zson_dict"
pg_dump: flagging inherited columns in subtables
pg_dump: reading indexes
pg_dump: reading indexes for table "public.zson_dict"
pg_dump: flagging indexes in partitioned tables
pg_dump: reading extended statistics
pg_dump: reading constraints
pg_dump: reading triggers
pg_dump: reading rewrite rules
pg_dump: reading policies
pg_dump: reading row security enabled for table "public.test"
pg_dump: reading policies for table "public.test"
pg_dump: reading row security enabled for table "public.zson_dict_dict_id_seq"
pg_dump: reading policies for table "public.zson_dict_dict_id_seq"
pg_dump: reading row security enabled for table "public.zson_dict"
pg_dump: reading policies for table "public.zson_dict"
pg_dump: reading publications
pg_dump: reading publication membership
pg_dump: reading publication membership for table "public.test"
pg_dump: reading subscriptions
pg_dump: reading large objects
pg_dump: reading dependency data
pg_dump: saving encoding = SQL_ASCII
pg_dump: saving standard_conforming_strings = on
pg_dump: saving search_path = 
pg_dump: saving database definition
pg_dump: dumping contents of table "public.test"
pg_dump: Dumping the contents of table "test" failed: PQgetResult() failed.
pg_dump: Error message from server: ERROR:  relation "zson_dict" does not exist
LINE 1: select word_id, word from zson_dict where dict_id = $1 order...
                                  ^
QUERY:  select word_id, word from zson_dict where dict_id = $1 order by word
pg_dump: The command was: COPY public.test (id, datetime, bid, ask, last, volume, orderbook) TO stdout;
<

pg_dump doesnt work with postgres 11.1 and zson.

**Comment by edmenendez** [comment] 2019-07-09 03:07
This commit seems to address the issue: https://github.com/bruce-one/zson/commit/8e59cdf4f92c7ffc0d0ba9a2d4e5673ffb292a9d

**Comment by lox** [comment] 2020-08-25 06:23
Would be great to get this fixed, @bruce-one, any chance of a PR?

**Comment by afiskon** [comment] 2021-04-21 12:00
I've checked. The issue was fixed with 8e59cdf4 a long time ago.

**Closed by afiskon** 2021-04-21 12:00 UTC

**Comment by Object905** [comment] 2023-04-12 06:24
I've got this in postgres  15.2 and zson 1.1.

select * FROM zson_dict; works when I connect to the database with psql.

**Comment by afiskon** [comment] 2023-04-12 13:26
@Object905 you are using a version released 6 years ago.

**Comment by Object905** [comment] 2023-04-14 09:36
@afiskon 
Weird thing is that I installed this extension by compiling it from master branch on latest commit, like in readme.

**Comment by afiskon** [comment] 2023-04-14 19:29
@Object905 you are right, I was able to reproduce this. I opened a new issue since this seems to be something related to the new version of PG https://github.com/postgrespro/zson/issues/25
