### ISSUE TITLE
pg_config: command not found and missing magic block

### ISSUE THREAD

**Issue by zheka-13** [postgrespro/zson#11] opened 2017-07-27 09:58 UTC
Hi,
When postgresql compiled from source and installed into default dirs pg_config not accessible from PATH. My suggestion below. One can easily change pg_config location in Makefile and there won't be no warnings. 
I suggest to modify Makefile:
1. Instead of 
   PGXS := $(shell pg_config --pgxs)
   do
   PG_CONFIG = pg_config
   PGXS := $(shell $(PG_CONFIG) --pgxs)
2. Add OBJS = zson.o. I don't understand why it's removed. Without it i can compile extension but get error when try to install it 
         incompatible library "/usr/local/pgsql/lib/zson.so": missing magic block

**Comment by afiskon** [comment] 2017-07-27 12:02
OK, I can confirm (2). Thanks a lot for reporting this. Fixed in 3d89ce8f CC: @arssher

I can't tell that I fully agree with (1) though. If pg_config is not in PATH it means that psql and other tools are not too. This is very atypical installation to say the least.

**Closed by afiskon** 2017-07-27 12:02 UTC

**Comment by arssher** [comment] 2017-07-27 14:37
2) Sorry, this is my fault: recently I have cleaned the Makefile, but forgot to remove MODULE_big var from it. See the following pull request where it is explained in the detail:
https://github.com/postgrespro/zson/pull/12

1) I support the idea: the situation in which you use for development several custom-built postgres'es is not rare. However, your solution is not good because it requires manual changes in the Makefile. In my pull request I improved this.
